# -*- coding: utf-8 -*-
"""GPT2-Medium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8ckh6-eHQu2KeRRBHQDBAXjVn8OmzmL

**Install Hugging Face + PEFT dependencies**
"""

!pip install datasets==2.19.1 transformers accelerate evaluate tqdm bitsandbytes peft

"""**Import Libraries for Model Training and LoRA Setup**"""

import math
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model

"""**Load GPT‑2 Medium with Quantization and LoRA Adapters**"""

model_name = "gpt2-medium"

# Quantization config
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=6.0
)

# Load quantized model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# LoRA config
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["c_attn"],  # GPT-2 uses c_attn layers
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)

# Wrap model with LoRA
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""**Load and Preview Blended Skill Talk Dataset**"""

raw_datasets = load_dataset("blended_skill_talk")
print(raw_datasets)
print(raw_datasets["train"][0])

"""**Preprocess and Tokenize Blended Skill Talk Dataset**"""

def preprocess_function(examples):
    texts = []
    for fm, gm in zip(examples.get("free_messages", []), examples.get("guided_messages", [])):
        if fm:
            texts.append(" ".join(fm))
        elif gm:
            texts.append(" ".join(gm))
        else:
            texts.append("")
    return tokenizer(texts, truncation=True, padding="max_length", max_length=128)

tokenized_datasets = raw_datasets.map(
    preprocess_function,
    batched=True,
    remove_columns=raw_datasets["train"].column_names
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print(tokenized_datasets)

"""**Train GPT‑2 Medium with LoRA and Log Epoch Metrics**"""

training_args = TrainingArguments(
    output_dir="./gpt2medium-bst",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    save_total_limit=2,
    fp16=True,
    save_steps=500,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

num_epochs = training_args.num_train_epochs
for epoch in range(num_epochs):
    print(f"\n=== Starting Epoch {epoch+1} ===")
    trainer.train(resume_from_checkpoint=None)

    # Validation metrics
    eval_results = trainer.evaluate()
    val_loss = eval_results["eval_loss"]
    val_ppl = math.exp(val_loss)

    # Training metrics: average loss from last epoch
    train_logs = [log for log in trainer.state.log_history if "loss" in log]
    train_loss = train_logs[-1]["loss"] if train_logs else None
    train_ppl = math.exp(train_loss) if train_loss else None

    print(f"\nEpoch {epoch+1} Summary:")
    print(f"  Train Loss: {train_loss:.4f}" if train_loss is not None else "  Train Loss: N/A")
    print(f"  Train PPL : {train_ppl:.4f}" if train_ppl is not None else "  Train PPL : N/A")
    print(f"  Val Loss  : {val_loss:.4f}")
    print(f"  Val PPL   : {val_ppl:.4f}")

"""**Evaluate Model on Test Set**"""

test_results = trainer.evaluate(tokenized_datasets["test"])
test_loss = test_results["eval_loss"]
test_ppl = math.exp(test_loss)

print(f"\nFinal Test Loss: {test_loss:.4f}")
print(f"Final Test Perplexity: {test_ppl:.4f}")