# -*- coding: utf-8 -*-
"""GPT-2 Small.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZadBUj9xdGnNM0bJPkRcB2l0-g_HWcF
"""

# CELL 1 — Imports

import torch
from torch.utils.data import DataLoader
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from datasets import load_dataset
from tqdm import tqdm
import math

# CELL 2 — Load Dolly 15k + 80/10/10 Split

from datasets import load_dataset

# Load Dolly 15k (this dataset loads cleanly)
dataset = load_dataset("databricks/databricks-dolly-15k")

# Format each example into a single text field
def format_example(example):
    prompt = f"Instruction: {example['instruction']}\n\n"
    if example["context"]:
        prompt += f"Context: {example['context']}\n\n"
    prompt += f"Response: {example['response']}"
    return {"text": prompt}

dataset = dataset.map(format_example)
dataset = dataset["train"]  # Dolly only has a 'train' split

# Create 80/10/10 split
splits = dataset.train_test_split(test_size=0.2, seed=42)
train_split = splits["train"]          # 80%
temp_split  = splits["test"]           # 20%

val_test = temp_split.train_test_split(test_size=0.5, seed=42)
val_split  = val_test["train"]         # 10%
test_split = val_test["test"]          # 10%

print("Train examples:", len(train_split))
print("Val examples:",   len(val_split))
print("Test examples:",  len(test_split))

# CELL 3 — Load Tokenizer

from transformers import GPT2TokenizerFast

tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

# GPT‑2 has no pad token by default, so we set it to EOS
tokenizer.pad_token = tokenizer.eos_token

print("Tokenizer loaded. Vocabulary size:", len(tokenizer))

# CELL 4 — Tokenize Dolly 15k Splits

import torch

MAX_LENGTH = 256  # good for Dolly 15k + GPT‑2 Small

def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )

# Tokenize each split
train_tok = train_split.map(tokenize_batch, batched=True, remove_columns=["text"])
val_tok   = val_split.map(tokenize_batch,   batched=True, remove_columns=["text"])
test_tok  = test_split.map(tokenize_batch,  batched=True, remove_columns=["text"])

# Set PyTorch tensor format
train_tok.set_format(type="torch", columns=["input_ids", "attention_mask"])
val_tok.set_format(type="torch",   columns=["input_ids", "attention_mask"])
test_tok.set_format(type="torch",  columns=["input_ids", "attention_mask"])

print("Tokenization complete.")
print("Train batches:", len(train_tok))
print("Val batches:",   len(val_tok))
print("Test batches:",  len(test_tok))

# CELL 5 — DataLoaders

from torch.utils.data import DataLoader

BATCH_SIZE = 2   # GPT‑2 Small + 256 tokens fits comfortably on Colab or your 5090

train_loader = DataLoader(train_tok, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_tok,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_tok,  batch_size=BATCH_SIZE, shuffle=False)

print("Train batches:", len(train_loader))
print("Val batches:",   len(val_loader))
print("Test batches:",  len(test_loader))

# CELL 6 — Load GPT‑2 Small Model

import torch
from transformers import GPT2LMHeadModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Load GPT‑2 Small
model = GPT2LMHeadModel.from_pretrained("gpt2")

# GPT‑2 has no pad token, so align it with EOS (same as tokenizer)
model.resize_token_embeddings(len(tokenizer))
model.config.pad_token_id = tokenizer.eos_token_id

model = model.to(device)

print("Model loaded and moved to device.")

# CELL 7 — Optimizer + Scheduler

from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

LEARNING_RATE = 5e-5
EPOCHS = 3

optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

# Total training steps = batches per epoch * number of epochs
total_steps = len(train_loader) * EPOCHS

# Linear warmup for 10% of training, then linear decay
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

print("Optimizer and scheduler ready.")
print("Total training steps:", total_steps)

# CELL 8 — Training Loop (with Validation Loss + Perplexity)

import torch
from tqdm import tqdm
import math

EPOCHS = 3
model.train()

for epoch in range(EPOCHS):
    print(f"\n===== Epoch {epoch+1}/{EPOCHS} =====")

    # -------------------------
    # Training
    # -------------------------
    train_loss = 0.0
    model.train()

    for batch in tqdm(train_loader, desc="Training", leave=False):
        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=input_ids
        )

        loss = outputs.loss
        train_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        scheduler.step()

    avg_train_loss = train_loss / len(train_loader)
    print(f"Train Loss: {avg_train_loss:.4f}")

    # -------------------------
    # Validation
    # -------------------------
    val_loss = 0.0
    model.eval()

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Validation", leave=False):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=input_ids
            )

            val_loss += outputs.loss.item()

    avg_val_loss = val_loss / len(val_loader)
    val_ppl = math.exp(avg_val_loss)

    print(f"Val Loss: {avg_val_loss:.4f}")
    print(f"Val Perplexity: {val_ppl:.4f}")

# CELL 9 — Test Evaluation (Loss + Perplexity)

model.eval()
test_loss = 0.0

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Testing", leave=False):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=input_ids
        )

        test_loss += outputs.loss.item()

avg_test_loss = test_loss / len(test_loader)
test_ppl = math.exp(avg_test_loss)

print(f"Test Loss: {avg_test_loss:.4f}")
print(f"Test Perplexity: {test_ppl:.4f}")

# CELL 10 — Epoch 0 Evaluation (Fresh Pretrained GPT-2 Small on Dolly 15k Val)

import torch
import math
from tqdm import tqdm
from transformers import AutoModelForCausalLM

# Load a fresh, un-finetuned GPT-2 Small
base_model = AutoModelForCausalLM.from_pretrained("gpt2").to(device)
base_model.eval()

val_loss_epoch0 = 0.0

with torch.no_grad():
    for batch in tqdm(val_loader, desc="Epoch 0 Validation", leave=False):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = base_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=input_ids
        )

        val_loss_epoch0 += outputs.loss.item()

avg_val_loss_epoch0 = val_loss_epoch0 / len(val_loader)
val_ppl_epoch0 = math.exp(avg_val_loss_epoch0)

print(f"Epoch 0 Val Loss: {avg_val_loss_epoch0:.4f}")
print(f"Epoch 0 Val Perplexity: {val_ppl_epoch0:.4f}")



