# -*- coding: utf-8 -*-
"""GPT-2 Large.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfeSueXVmNX16ajcUTeT8R6iO-zwWxq4
"""

# CELL 1
!pip install transformers accelerate datasets bitsandbytes peft sentencepiece

# CELL 2
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import load_dataset
from torch.utils.data import DataLoader
from torch.cuda.amp import GradScaler, autocast
import torch.nn.functional as F
import math

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# CELL 3 — Create train (12k), validation (1.5k), test (1.5k)

from datasets import load_dataset

dataset = load_dataset("databricks/databricks-dolly-15k")["train"]

# First split: 12k train, 3k temp
splits = dataset.train_test_split(test_size=3000, shuffle=True, seed=42)
train_split = splits["train"]
temp_split = splits["test"]

# Second split: 1.5k validation, 1.5k test
val_test = temp_split.train_test_split(test_size=1500, shuffle=True, seed=42)
val_split = val_test["train"]
test_split = val_test["test"]

print("Train size:", len(train_split))
print("Validation size:", len(val_split))
print("Test size:", len(test_split))

# CELL 4
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["c_attn", "c_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# CELL 5
dataset = load_dataset("databricks/databricks-dolly-15k")

def format_example(example):
    prompt = f"Instruction: {example['instruction']}\n\n"
    if example["context"]:
        prompt += f"Context: {example['context']}\n\n"
    prompt += f"Response: {example['response']}"
    return {"text": prompt}

dataset = dataset.map(format_example)
dataset = dataset["train"].train_test_split(test_size=0.1)

# CELL 6 — Build a text field + tokenize all splits

def build_text(example):
    # Combine Dolly fields into a single training string
    instruction = example.get("instruction", "")
    context     = example.get("context", "")
    response    = example.get("response", "")

    # Format similar to Alpaca / Dolly style
    example["text"] = (
        f"Instruction: {instruction}\n"
        f"Context: {context}\n"
        f"Response: {response}"
    )
    return example

# Build text field for each split
train_built = train_split.map(build_text)
val_built   = val_split.map(build_text)
test_built  = test_split.map(build_text)

# Tokenizer function
def tokenize(batch):
    tokens = tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

# Tokenize all splits
tokenized_train = train_built.map(tokenize, batched=True)
tokenized_val   = val_built.map(tokenize, batched=True)
tokenized_test  = test_built.map(tokenize, batched=True)

# Remove unused columns
remove_cols = ["instruction", "context", "response", "category", "text"]

tokenized_train = tokenized_train.remove_columns(remove_cols)
tokenized_val   = tokenized_val.remove_columns(remove_cols)
tokenized_test  = tokenized_test.remove_columns(remove_cols)

# Set tensor format
tokenized_train.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

# CELL 7 — DataLoaders

from torch.utils.data import DataLoader

train_loader = DataLoader(tokenized_train, batch_size=1, shuffle=True)
val_loader   = DataLoader(tokenized_val,   batch_size=1, shuffle=False)
test_loader  = DataLoader(tokenized_test,  batch_size=1, shuffle=False)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

# CELL 8
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4)
scaler = GradScaler()
model.train()

from tqdm import tqdm

# CELL 9
epochs = 3

for epoch in range(epochs):
    print(f"\n===== Epoch {epoch+1} / {epochs} =====")
    total_loss = 0

    # TRAINING
    for step, batch in enumerate(tqdm(train_loader, desc="Training", leave=False)):
        batch = {k: v.to(device) for k, v in batch.items()}

        with torch.amp.autocast("cuda", dtype=torch.bfloat16):
            outputs = model(
                input_ids=batch["input_ids"],
                attention_mask=batch["attention_mask"],
                labels=batch["labels"]
            )
            loss = outputs.loss

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad()

        total_loss += loss.item()

        if step % 100 == 0:
            print(f"Step {step} | Loss: {loss.item():.4f}")

    avg_train_loss = total_loss / len(train_loader)

    # VALIDATION
    model.eval()
    val_loss = 0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Validation", leave=False):
            batch = {k: v.to(device) for k, v in batch.items()}
            with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                outputs = model(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"],
                    labels=batch["labels"]
                )
                val_loss += outputs.loss.item()

    avg_val_loss = val_loss / len(val_loader)
    val_ppl = math.exp(avg_val_loss)

    print(f"\n===== END OF EPOCH {epoch+1} SUMMARY =====")
    print(f"Train Loss: {avg_train_loss:.4f}")
    print(f"Val Loss:   {avg_val_loss:.4f}")
    print(f"Val PPL:    {val_ppl:.4f}")

    model.train()

# --- Cell 9.3: Save trained model weights ---

save_path = "gpt2-small-epoch1-trained"

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print(f"Model saved to: {save_path}")

# CELL 9.9 — Final Validation Cell (Correct for Your Batch Format)

import torch
import math
from tqdm import tqdm

model.eval()
val_loss = 0.0
count = 0

with torch.no_grad():
    for batch in tqdm(val_loader, desc="Validation", leave=False):

        # ----------------------------------------------------
        # Your batch format:
        # batch["input_ids"] is a list of 256 tensors, each (1,)
        # ----------------------------------------------------
        if isinstance(batch, dict) and isinstance(batch["input_ids"], list):

            # Convert list of (1,) tensors → (256, 1) → (256,) → (1, 256)
            input_ids = torch.stack(batch["input_ids"]).squeeze(1).unsqueeze(0).to(device)
            attention_mask = torch.stack(batch["attention_mask"]).squeeze(1).unsqueeze(0).to(device)
            labels = torch.stack(batch["labels"]).squeeze(1).unsqueeze(0).to(device)

        else:
            # Skip anything unexpected
            continue

        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------
        with torch.amp.autocast("cuda", dtype=torch.bfloat16):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

        loss = outputs.loss.item()

        # Skip NaN batches
        if math.isnan(loss):
            continue

        val_loss += loss
        count += 1

# ----------------------------------------------------
# Final metrics
# ----------------------------------------------------
avg_val_loss = val_loss / max(count, 1)

# Safe perplexity (avoid overflow)
val_ppl = math.exp(avg_val_loss) if avg_val_loss < 50 else float("inf")

print(f"Val Loss: {avg_val_loss:.4f}")
print(f"Val PPL:  {val_ppl}")

# --- Cell 9.51: Inspect a single batch ---
batch = next(iter(val_loader))
print("Batch type:", type(batch))
print("Batch content:", batch)

batch = next(iter(val_loader))
print(batch)

# CELL 9.8 — Inspect First Validation Batch (RAW OUTPUT)

batch = next(iter(val_loader))

print("=== BATCH TYPE ===")
print(type(batch))

print("\n=== BATCH CONTENT ===")
print(batch)

# If it's a dict, show keys
if isinstance(batch, dict):
    print("\n=== DICT KEYS ===")
    print(batch.keys())

    # Show shapes if tensors
    for k, v in batch.items():
        if hasattr(v, "shape"):
            print(f"{k} shape:", v.shape)
        elif isinstance(v, list):
            print(f"{k} is a list of length:", len(v))

# If it's a list, show element types
elif isinstance(batch, list):
    print("\n=== LIST ELEMENT TYPES ===")
    for i, item in enumerate(batch):
        print(f"Index {i}: type={type(item)}")
        if hasattr(item, "shape"):
            print("  shape:", item.shape)

# CELL 10 — Patched Final Test Evaluation (Handles Your Batch Format)

import torch
import math
from tqdm import tqdm

model.eval()
test_loss = 0.0
count = 0

print("\n===== Running Final Test Evaluation =====")

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Testing", leave=False):

        # ----------------------------------------------------
        # Your batch format:
        # batch["input_ids"] is a list of 256 tensors, each (1,)
        # ----------------------------------------------------
        if isinstance(batch, dict) and isinstance(batch["input_ids"], list):

            # Convert list of (1,) tensors → (256, 1) → (256,) → (1, 256)
            input_ids = torch.stack(batch["input_ids"]).squeeze(1).unsqueeze(0).to(device)
            attention_mask = torch.stack(batch["attention_mask"]).squeeze(1).unsqueeze(0).to(device)
            labels = torch.stack(batch["labels"]).squeeze(1).unsqueeze(0).to(device)

        else:
            # Skip anything unexpected
            continue

        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------
        with torch.amp.autocast("cuda", dtype=torch.bfloat16):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

        loss = outputs.loss.item()

        # Skip NaN batches
        if math.isnan(loss):
            continue

        test_loss += loss
        count += 1

# ----------------------------------------------------
# Final metrics
# ----------------------------------------------------
avg_test_loss = test_loss / max(count, 1)
test_ppl = math.exp(avg_test_loss) if avg_test_loss < 50 else float("inf")

print("\n===== FINAL TEST RESULTS =====")
print(f"Test Loss: {avg_test_loss:.4f}")
print(f"Test Perplexity: {test_ppl:.4f}")

# ----------------------------------------------------
# Sample generations from the test split
# ----------------------------------------------------
print("\n===== SAMPLE GENERATIONS =====")

for i in range(3):
    sample = tokenized_test[i]

    # Convert list-of-tensors sample into proper shape
    input_ids = torch.tensor(sample["input_ids"]).unsqueeze(0).to(device)

    output = model.generate(
        input_ids=input_ids,
        max_new_tokens=80,
        do_sample=True,
        temperature=0.8,
        top_p=0.9
    )

    print(f"\n--- Sample {i+1} ---")
    print(tokenizer.decode(output[0], skip_special_tokens=True))