# -*- coding: utf-8 -*-
"""Mask2FormerSwinBaseCOCOPanoptic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irCGQNyOqr6dwre38XgX26u6VOOSn_sY
"""

!pip install -q transformers accelerate opencv-python pillow
print("Dependencies installed.")

import cv2
import numpy as np
from PIL import Image
import torch
from google.colab import files
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation

model_id = "facebook/mask2former-swin-base-coco-panoptic"
processor = AutoImageProcessor.from_pretrained(model_id)
model = Mask2FormerForUniversalSegmentation.from_pretrained(model_id).to("cuda")

print("Mask2Former Swin-B COCO Panoptic loaded.")

print("Upload your short video (MP4 recommended).")
uploaded = files.upload()

# Grab the uploaded filename
input_video = list(uploaded.keys())[0]
print("Video uploaded:", input_video)

output_video = "panoptic_output.mp4"
print("Output will be saved as:", output_video)

def panoptic_segment_frame(frame):
    # Convert to RGB + PIL
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(rgb)

    # Prepare inputs
    inputs = processor(images=pil_img, return_tensors="pt").to("cuda")

    # Run model
    with torch.no_grad():
        outputs = model(**inputs)

    # Panoptic post-processing
    result = processor.post_process_panoptic_segmentation(
        outputs,
        target_sizes=[pil_img.size[::-1]]
    )[0]

    seg_map = result["segmentation"].cpu().numpy()

    # Create colored overlay
    colored = np.zeros_like(rgb)
    unique_ids = np.unique(seg_map)

    rng = np.random.default_rng(12345)
    colors = {uid: rng.integers(0, 255, size=3) for uid in unique_ids}

    for uid in unique_ids:
        colored[seg_map == uid] = colors[uid]

    blended = (0.6 * rgb + 0.4 * colored).astype(np.uint8)

    # Convert back to BGR
    return cv2.cvtColor(blended, cv2.COLOR_RGB2BGR)

cap = cv2.VideoCapture(input_video)

fps = cap.get(cv2.CAP_PROP_FPS)
w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
writer = cv2.VideoWriter(output_video, fourcc, fps, (w, h))

frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    segmented = panoptic_segment_frame(frame)
    writer.write(segmented)

    frame_idx += 1
    print(f"Processed frame {frame_idx}")

cap.release()
writer.release()

print("\nPanoptic video created:", output_video)

from google.colab import files
files.download(output_video)