# -*- coding: utf-8 -*-
"""OPT-350M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G51hYiLlqUDp-mWpdwZCULLiisZmCcWK

**Downgrade Datasets to 2.19.1**
"""

# Cell 1
# Downgrade datasets to 2.19.1
!pip install datasets==2.19.1

"""**Upgrade Hugging Face Datasets**"""

# Cell 2
!pip install -U datasets

"""**Install Core Hugging Face Libraries**"""

# Cell 3
!pip install datasets==2.19.1 transformers accelerate evaluate tqdm

"""**Install Bitsandbytes**"""

# Cell 4 — Install bitsandbytes
!pip install -U bitsandbytes

"""**Upgrade Transformers + Accelerate**"""

# Cell 5 — Upgrade transformers + accelerate
!pip install -U transformers accelerate

"""**Import Core Libraries**"""

# Cell 5.5
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments
from datasets import load_dataset
import evaluate
from tqdm import tqdm

"""**Load OPT-350M Model + Tokenizer**"""

# Cell 6 — Load OPT-350M model + tokenizer

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "facebook/opt-350m"

# Configure 8-bit quantization for Colab efficiency
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=6.0
)

# Load the quantized model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

"""**Install PEFT**"""

# Cell 7
# Install PEFT
!pip install peft

from peft import LoraConfig, get_peft_model

# Define LoRA config
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q_proj","v_proj"],  # typical for OPT
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)

# Wrap the quantized model with LoRA adapters
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""**Load the Blended Skill Talk Dataset**"""

# Cell 8
from datasets import load_dataset

raw_datasets = load_dataset("blended_skill_talk")
print(raw_datasets)

"""**Tokenize Blended Skill Talk Dataset**"""

# Cell 9 — Tokenize Blended Skill Talk dataset

from transformers import DataCollatorForLanguageModeling

# Function to join dialogue turns into a single string
def preprocess_function(examples):
    # Use free_messages if available, otherwise guided_messages
    texts = []
    for fm, gm in zip(examples.get("free_messages", []), examples.get("guided_messages", [])):
        if fm:
            texts.append(" ".join(fm))
        elif gm:
            texts.append(" ".join(gm))
        else:
            texts.append("")
    return tokenizer(texts, truncation=True, padding="max_length", max_length=128)

# Apply preprocessing
tokenized_datasets = raw_datasets.map(
    preprocess_function,
    batched=True,
    remove_columns=raw_datasets["train"].column_names
)

# Data collator for language modeling
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print(tokenized_datasets)

"""**Full Training Setup with Per-epoch Metrics**"""

# Cell 10 — Full training setup with per-epoch metrics

import math
from transformers import Trainer, TrainingArguments

# Training arguments (no evaluation_strategy/logging_strategy here)
training_args = TrainingArguments(
    output_dir="./opt350m-bst",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    save_total_limit=2,
    fp16=True,
    save_steps=500
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

# Run training + evaluation per epoch
num_epochs = training_args.num_train_epochs
for epoch in range(num_epochs):
    print(f"\n=== Starting Epoch {epoch+1} ===")
    trainer.train(resume_from_checkpoint=None)

    # Validation metrics
    eval_results = trainer.evaluate()
    val_loss = eval_results["eval_loss"]
    val_ppl = math.exp(val_loss)

    # Training metrics: average loss from last epoch
    train_logs = [log for log in trainer.state.log_history if "loss" in log]
    train_loss = train_logs[-1]["loss"] if train_logs else None
    train_ppl = math.exp(train_loss) if train_loss else None

    print(f"\nEpoch {epoch+1} Summary:")
    print(f"  Train Loss: {train_loss:.4f}" if train_loss is not None else "  Train Loss: N/A")
    print(f"  Train PPL : {train_ppl:.4f}" if train_ppl is not None else "  Train PPL : N/A")
    print(f"  Val Loss  : {val_loss:.4f}")
    print(f"  Val PPL   : {val_ppl:.4f}")