# -*- coding: utf-8 -*-
"""Pythia-1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqgrjMIFUij-QqtB7QyWmmE6lw0y9EIH

**Install Required Libraries**
"""

# CELL 1
!pip install -q transformers accelerate datasets peft trl

"""**Load Dolly Dataset and Create Train/Test Split**"""

# CELL 2 — Load Dolly and Create 3-Way Split (80/10/10)

from datasets import load_dataset

# Load Dolly 15k
dataset = load_dataset("databricks/databricks-dolly-15k")

# First split: 80% train, 20% temp
split1 = dataset["train"].train_test_split(test_size=0.20, seed=42)

# Second split: temp → 10% val, 10% test
split2 = split1["test"].train_test_split(test_size=0.50, seed=42)

train_dataset = split1["train"]     # 80% = 12,000 examples
eval_dataset  = split2["train"]     # 10% = 1,500 examples
test_dataset  = split2["test"]      # 10% = 1,500 examples

print("Train size:", len(train_dataset))
print("Validation size:", len(eval_dataset))
print("Test size:", len(test_dataset))

"""**Format Dolly Examples into Instruction–Response Text**"""

# CELL 3 — Apply Formatting + Tokenization to Train / Val / Test

def format_dolly(example):
    """
    Converts Dolly-style instruction data into a single text field.
    Expected keys: 'instruction', 'context', 'response'
    """
    instruction = example.get("instruction", "")
    context = example.get("context", "")
    response = example.get("response", "")

    text = f"Instruction: {instruction}\n"
    if context:
        text += f"Context: {context}\n"
    text += f"Response: {response}"

    return {"text": text}


# Apply Dolly formatting (creates the "text" field)
train_dataset = train_dataset.map(format_dolly)
eval_dataset  = eval_dataset.map(format_dolly)
test_dataset  = test_dataset.map(format_dolly)


# Tokenize all splits
def tokenize_with_labels(batch):
    tokens = tokenizer(batch["text"])
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

train_dataset = train_dataset.map(tokenize_with_labels, batched=True)
eval_dataset  = eval_dataset.map(tokenize_with_labels, batched=True)
test_dataset  = test_dataset.map(tokenize_with_labels, batched=True)


# IMPORTANT: KEEP "text" because your SFTTrainer version requires it
keep_cols = ["text", "input_ids", "attention_mask", "labels"]

train_dataset = train_dataset.remove_columns(
    [col for col in train_dataset.column_names if col not in keep_cols]
)
eval_dataset = eval_dataset.remove_columns(
    [col for col in eval_dataset.column_names if col not in keep_cols]
)
test_dataset = test_dataset.remove_columns(
    [col for col in test_dataset.column_names if col not in keep_cols]
)

print("Formatted + tokenized:")
print("Train:", len(train_dataset))
print("Validation:", len(eval_dataset))
print("Test:", len(test_dataset))

"""**Load Base Model and Tokenizer (Pythia‑1B)**"""

# CELL 4
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "EleutherAI/pythia-1b"

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)

"""**Configure LoRA Parameters for Fine‑Tuning**"""

# CELL 5
from peft import LoraConfig

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

"""**Set Training Arguments for Fine‑Tuning**"""

# CELL 6
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="pythia1b-dolly-lora",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,   # effective batch size = 8
    warmup_steps=20,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=10,
    save_steps=500,
    save_total_limit=2,
    fp16=True,
    report_to="none"
)

# CELL 6.5 - RELOAD BASE MODEL (NO LORA ATTACHED)
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    "EleutherAI/pythia-1b",
    device_map="auto",
    torch_dtype="auto"
)

"""**Initialize SFT Trainer with LoRA and Training Configuration**"""

# CELL 7 — Trainer Setup with Validation Each Epoch

from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="pythia1b-dolly-lora",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=50,
    save_strategy="no",
    report_to="none",
    eval_strategy="epoch",
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    peft_config=lora_config,
)

"""**Prepare Dataset, Tokenize, Create Splits, and Run Training with Final Test Evaluation**"""

# ============================
#             CELL 8 good+
#   Training + Val + Test Eval
# ============================

import math
from transformers import TrainerCallback

# ---- Callback: print validation PPL at end of each epoch ----
class EpochSummaryCallback(TrainerCallback):
    def on_evaluate(self, args, state, control, metrics, **kwargs):
        # This is called immediately after each evaluation pass
        eval_loss = metrics.get("eval_loss", None)

        print("\n==============================")
        print(f" Epoch {int(state.epoch)} Validation Summary")
        print("==============================")

        if eval_loss is not None:
            eval_ppl = math.exp(eval_loss)
            print(f"Validation Loss: {eval_loss:.4f}")
            print(f"Validation Perplexity: {eval_ppl:.4f}")
        else:
            print("No eval_loss found in metrics.")

        print("==============================\n")


# ---- IMPORTANT: avoid OOM and fp16 gradient-scaler errors ----
training_args.per_device_eval_batch_size = 1
training_args.fp16 = False
training_args.bf16 = True
training_args.fp16_full_eval = False
training_args.bf16_full_eval = True


# ---- Trainer Setup ----
trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=training_args,
    callbacks=[EpochSummaryCallback()],
)

# ---- Train ----
trainer.train()

# ---- Final Test Evaluation ----
print("\n==============================")
print(" Final Test Evaluation")
print("==============================")

test_results = trainer.evaluate(test_dataset)

test_loss = test_results.get("eval_loss")
if test_loss is not None:
    test_ppl = math.exp(test_loss)
    print(f"Test Loss: {test_loss:.4f}")
    print(f"Test Perplexity: {test_ppl:.4f}")
else:
    print("No eval_loss found in test_results.")

print("==============================\n")

"""**Save Trained LoRA Adapter Weights**"""

# CELL 9 — Save LoRA Adapter

adapter_path = "pythia1b-dolly-lora-adapter"
trainer.model.save_pretrained(adapter_path)

print("LoRA adapter saved to:", adapter_path)

"""**Run Inference Using the Base Model with the Loaded LoRA Adapter**"""

# CELL 10 — Inference with LoRA Adapter (updated for variety)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import os

base_model_name = "EleutherAI/pythia-1b"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_model_name)

# Load base model
model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    dtype=torch.float16,
    device_map="auto"
)

# Load LoRA adapter using absolute path
adapter_path = os.path.abspath("pythia1b-dolly-lora-adapter")
model = PeftModel.from_pretrained(model, adapter_path)

# Inference function with your updated generation settings
def generate(prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=1.2,
        top_p=0.85,
        top_k=50,
        repetition_penalty=1.15,
    )
    return tokenizer.decode(output[0], skip_special_tokens=True)

# Test it — this prompt forces a new question + answer each run
print(generate(
    "Generate a completely new science question that has not been asked before, "
    "and then provide a clear answer to it."
))