# -*- coding: utf-8 -*-
"""Ragpipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH66bekUDDM3SidJtPliZqFwXwYBJRZH
"""

# Cell 0
!pip install groq

# Cell 1 — Imports

import numpy as np
from sentence_transformers import SentenceTransformer
from groq import Groq

# Cell 2 — Load Documents

documents = [
    "Mount Everest is the tallest mountain in the world.",
    "The Great Wall of China is visible from space only in myth.",
    "The capital of France is Paris.",
    "Alexander Fleming discovered penicillin in 1928.",
    "The Pacific Ocean is the largest ocean on Earth.",
    "Albert Einstein developed the theory of relativity.",
    "The speed of light is approximately 299,792 kilometers per second.",
    "The Sahara Desert is the largest hot desert in the world.",
    "The Amazon Rainforest produces around 20% of the world's oxygen.",
    "The Nile River is commonly considered the longest river in the world.",
    "Leonardo da Vinci painted the Mona Lisa.",
    "Earth revolves around the Sun once every 365 days.",
    "The human brain contains roughly 86 billion neurons.",
    "Jupiter is the largest planet in the Solar System.",
    "The Statue of Liberty was a gift from France to the United States.",
    "The Pyramids of Giza are over 4,500 years old.",
    "Water boils at 100 degrees Celsius at sea level.",
    "The Roman Empire fell in 476 AD.",
    "The Moon's gravity causes ocean tides on Earth.",
    "The speed of sound in air is about 343 meters per second.",
    "The Eiffel Tower is located in Paris, France.",
    "The Mariana Trench is the deepest part of the ocean.",
    "The Andes is the longest continental mountain range.",
    "The Dead Sea is one of the saltiest bodies of water on Earth.",
    "The Taj Mahal was built by Mughal emperor Shah Jahan.",
    "The Leaning Tower of Pisa is famous for its tilt.",
    "The Colosseum in Rome was used for gladiator battles.",
    "The Great Barrier Reef is the largest coral reef system.",
    "The Himalayas were formed by tectonic plate collision.",
    "The Yangtze River is the longest river in Asia.",
    "The Sahara spans multiple countries in North Africa.",
    "The Arctic Circle marks the northernmost major circle of latitude.",
    "The Antarctic is the coldest place on Earth.",
    "The Golden Gate Bridge is located in San Francisco.",
    "The Burj Khalifa is the tallest building in the world.",
    "The Panama Canal connects the Atlantic and Pacific Oceans.",
    "The Suez Canal connects the Mediterranean Sea to the Red Sea.",
    "The Amazon River carries more water than any other river.",
    "The Mediterranean Sea borders Europe, Africa, and Asia.",
    "The Black Sea is connected to the Mediterranean through the Bosporus.",
    "The Caspian Sea is the largest inland body of water.",
    "The Great Lakes contain about 21% of the world's surface freshwater.",
    "The Mississippi River flows from Minnesota to the Gulf of Mexico.",
    "The Rocky Mountains stretch from Canada to New Mexico.",
    "The Alps are the highest mountain range in Europe.",
    "The Pyrenees form a natural border between France and Spain.",
    "The Danube River flows through multiple European capitals.",
    "The Rhine River is one of Europe's major waterways.",
    "The Sahara Desert can reach temperatures over 50 degrees Celsius.",
    "The Gobi Desert is located in China and Mongolia.",
    "The Serengeti is known for its annual wildebeest migration.",
    "The Galápagos Islands inspired Darwin’s theory of evolution.",
    "The Great Rift Valley runs through Eastern Africa.",
    "The Kalahari Desert covers parts of Botswana and Namibia.",
    "The Amazon Basin contains the world's largest rainforest.",
    "The Congo River is the deepest river in the world.",
    "The Yangtze River is home to the Three Gorges Dam.",
    "The Mekong River flows through Southeast Asia.",
    "The Himalayas include Mount Everest and K2.",
    "The Appalachian Mountains are among the oldest in the world.",
    "The Atacama Desert is one of the driest places on Earth.",
    "The Baltic Sea is bordered by Scandinavian and Baltic countries.",
    "The Caribbean Sea is known for its tropical climate.",
    "The Persian Gulf is rich in oil reserves.",
    "The Red Sea is one of the saltiest seas in the world.",
    "The Bay of Bengal is the largest bay in the world.",
    "The Strait of Gibraltar separates Europe and Africa.",
    "The Bering Strait separates Russia and Alaska.",
    "The English Channel separates England and France.",
    "The Himalayas influence climate patterns across Asia.",
    "The Amazon Rainforest is home to millions of species.",
    "The Sahara Desert expands and contracts over time.",
    "The Dead Sea lies at the lowest land elevation on Earth.",
    "The Great Wall of China stretches over 13,000 miles.",
    "The Eiffel Tower was completed in 1889.",
    "The Colosseum could hold over 50,000 spectators.",
    "The Taj Mahal is made of white marble.",
    "The Pyramids of Giza were built as tombs for pharaohs.",
    "The Statue of Liberty stands on Liberty Island.",
    "The Leaning Tower of Pisa leans due to unstable soil.",
    "The Great Barrier Reef is threatened by coral bleaching.",
    "The Burj Khalifa stands over 828 meters tall.",
    "The Panama Canal was completed in 1914.",
    "The Suez Canal was expanded in 2015.",
    "The Amazon River flows through Brazil.",
    "The Nile River flows northward.",
    "The Mississippi River is a major U.S. trade route.",
    "The Alps include Mont Blanc.",
    "The Andes include Aconcagua.",
    "The Rocky Mountains include Mount Elbert.",
    "The Pyrenees include Pico de Aneto.",
    "The Danube flows through Vienna, Budapest, and Belgrade.",
    "The Rhine flows through Germany and the Netherlands.",
    "The Gobi Desert has extreme temperature swings.",
    "The Serengeti is located in Tanzania.",
    "The Galápagos Islands belong to Ecuador.",
    "The Great Rift Valley stretches from Lebanon to Mozambique.",
    "The Kalahari Desert supports diverse wildlife.",
    "The Congo River flows through Central Africa.",
    "The Mekong River flows into the South China Sea."
]

# Cell 3 — Groq Client

client = Groq

# Cell 4 — Load Embedding Model

embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Cell 5 — Generate Embeddings

embeddings = embedder.encode(documents, convert_to_numpy=True)
embeddings = np.array(embeddings)

print("Embeddings shape:", embeddings.shape)

# Cell 6 — Normalize Embeddings

norm_embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

print("Normalized embeddings shape:", norm_embeddings.shape)

# Cell 7 — FIXED RAG Function

def rag(query, k=3):
    # Encode and normalize the query
    q = embedder.encode([query], convert_to_numpy=True)
    q = q / np.linalg.norm(q)

    # Cosine similarity (FIX: flatten to 1D)
    sims = (norm_embeddings @ q.T).flatten()

    # Top‑k indices
    top_k = sims.argsort()[-k:][::-1]

    # Retrieve documents
    retrieved = [(documents[i], float(sims[i])) for i in top_k]

    # Build context block
    context = "\n".join([f"- {doc}" for doc, score in retrieved])

    prompt = f"""
Use ONLY the context below to answer the question.
If the answer is not in the context, say you don't know.

Context:
{context}

Question: {query}

Answer:
"""

    resp = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )

    return retrieved, resp.choices[0].message.content.strip()

# Cell 8 — Run 10 RAG Tests

tests = [
    "Who discovered penicillin?",
    "What is the capital of France?",
    "What is the tallest mountain in the world?",
    "Which ocean is the largest?",
    "What causes ocean tides?",
    "Which desert is the largest hot desert?",
    "What river is the longest in the world?",
    "Who painted the Mona Lisa?",
    "What is the deepest part of the ocean?",
    "Which planet is the largest in the Solar System?"
]

for i, query in enumerate(tests, 1):
    print(f"\n=== Test {i}: {query} ===")
    retrieved, answer = rag(query)
    print("Retrieved:")
    for doc, score in retrieved:
        print(f"{score:.3f} — {doc}")
    print("\nAnswer:")
    print(answer)
    print("-" * 60)